CLASS /eacm/bp_i_rpriepmde DEFINITION
  PUBLIC
  ABSTRACT
  FINAL FOR BEHAVIOR OF /eacm/i_rpriepmde.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS /eacm/bp_i_rpriepmde IMPLEMENTATION.
ENDCLASS.
